### ISSUE TITLE
[Feature request] Implement as a fcitx module instead of engine

### ISSUE THREAD

**Issue by wengxt** [GaZaTu/im-emoji-picker#1]
When it’s implemented as an engine, it means user have to switch to use it.

Instead , implement it as a module allows you to use it inconjunction with any other engines.

You may want to check https://github.com/fcitx/fcitx5/tree/master/src/modules/quickphrase (quickphrase already have some built in emoji, btw)

Also, while you can use your own window, it won’t work if you’re using wayland.

I’d suggest you use fcitx to display instead of using your own window.

**Comment by GaZaTu** [comment]
> When it’s implemented as an engine, it means user have to switch to use it.

True and it's bothersome. 😅 (although you could work around this issue if you define a system hotkey to call the fcitx-remote command to switch to the emoji picker input method engine)

> implement it as a module

I did not know about fcitx5 modules before and a quick glance at quickphrase wasn't very helpful (idk how they get any events like when the window should be opened or the user is typing something).

> Also, while you can use your own window, it won’t work if you’re using wayland.

But if you're saying that implementing this as a module instead of an engine means i can't use my own window then i don't think i will change anything as it currently works with wayland. ¯\\_(ツ)_/¯

**Comment by wengxt** [comment]
I mean you can use module to implement a "temp" mode.

For example, the unicode module, will use instance->watchEvent to listen to whether ctrl+shift+alt+u is pressed (https://github.com/fcitx/fcitx5/blob/3a46edf0c83c40285e5fd8dc76f9b95990024e47/src/modules/unicode/unicode.cpp#L87), if so, it will grab all the keyevent before the engine (https://github.com/fcitx/fcitx5/blob/3a46edf0c83c40285e5fd8dc76f9b95990024e47/src/modules/unicode/unicode.cpp#L114). You just use this callback to replace your current InputMethodEngine::keyEvent and that's it.

In this way, your emoji picker is not an engine, but a feature that can be used with any engine. 

For example, you define ctrl + alt + e as the key to trigger your emoji picker. First you listen to the key event post the input method engine stage (`watchEvent(EventType::InputContextKeyEvent, EventWatcherPhase::Default)`), if it's not handled, then you flip a bool flag in your own input context property to mark this input context is under "emoji picker state".

And use another event watcher callback to filter all the key if this bool flag is true with (`watchEvent(EventType::InputContextKeyEvent, EventWatcherPhase::PreInputMethod)`). PreInputMethod means it's handled before InputMethodEngine::keyEvent, so all the key goes your addon instead of engine.

The window issue on wayland is independent of this "module but not engine" issue. Just to point out this doesn't work on wayland for now and you might want to consider an alternative solution (It's possible to detect whether system is under wayland). 

E.g. with fcitx's own ui you can do sth like this: (<kbd>meta</kbd> + <kbd>`</kbd> and press <kbd>s</kbd> to show the same thing in the screen shot
![图片](https://user-images.githubusercontent.com/259684/220217183-f59ce3f6-81b4-42a9-9bf2-9e5f11af03a4.png) )

**Comment by schrmh** [comment]
Module would be preferable so that one would not switch to the picker by accident when switching between input method groups.
At least if the fancy window is kept (&fixed, since it is outside of the screen in some cases just like the predecessor of this tool... Meanwhile the built-in window of fcitx5 handles this well) and if it is as convenient as this script (I use this with input method groups I named DE, DE/JA, DE/CN and Emoji. DE/JA and DE/CN have several input methods and DE and Emoji only one — im-emoji-picker is the one in Emoji — and the switching between im-emoji-picker and the previous input method group & method works pretty well):
```sh
#!/bin/sh
g="$(fcitx5-remote -q)"
s="$(fcitx5-remote -n)"
[ "$g" = "Emoji" ] && exit
fcitx5-remote -g "Emoji"

sleep 0.2
window_id=$(xwininfo -name im-emoji-picker | awk '/Window id:/ {print $4}')
current_state=$(xwininfo -id $window_id | awk '/Map State:/ {print $3}')
while [ "$current_state" != "IsUnMapped" ]
do
	sleep 0.1
	current_state=$(xwininfo -id $window_id | awk '/Map State:/ {print $3}')
done
fcitx5-remote -g $g
fcitx5-remote -s $s
```

**Comment by GaZaTu** [comment]
@wengxt @schrmh you may take a look at #2

**Comment by schrmh** [comment]
Thanks, I really like how it works now.
Minor things I noticed: 
- I can't press that shortcut on QWERTZ layout (when I press the shift key I input colon instead of dot) but it's good that it's configurable so it's not really a problem.
- A few options like windowOpacity and useSystemEmojiFont require a restart of fcitx5 until they apply. Consider stating that in the README and maybe move them in their own group in your config file
- The window closes when I move the window that had focus before I pressed the shortcut. Okay, to be fair, in almost all windows this is also the case with engines but for some reason this is not the case with engines when I try it with Discord. So yeah, technically im-emoji-picker is more consistent here by vanishing all the time but it would be nice if it was (optionally) the other way around (staying so that input is not lost). Maybe @wengxt could say/do something here cause this likely requires changes in fcitx5 as well.

**Comment by GaZaTu** [comment]
@schrmh 

> A few options like windowOpacity and useSystemEmojiFont require a restart...

you're right, i'll update the README accordingly but i don't think i'll make a new settings group.

> The window closes when I move the window that had focus before I pressed the shortcut...

mhh ye i know what you mean. The IMF sends the reset event or something. I guess i can add a setting so you can ignore the event.

> Btw. I had to use cmake to compile this, neither the install.sh nor the AUR package work atm.

uhh ok i'll check whats up with that 🫣
